### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by StefanENC** [app-generator/react-material-dashboard#1]
Hi,

What am I supposed to do on this repo?
Login, Register, and Lock pages are non-existent and the "Upgrade to PRO" page says that they should not exist on this version.

**Comment by app-generator** [comment]
Hello @StefanENC, 

Sorry, I didn't check the existence of the auth pages.

**Comment by app-generator** [comment]
The task is suspended until login/register pages are provided. 
Ty @StefanENC for your assistance.
